### ISSUE TITLE
Read me to run this??

### ISSUE THREAD

**Issue by ghost** [RedCarrottt/nvmon#1]
Is there are read me to run this?

**Comment by RedCarrottt** [comment]
Hello, I've made [README.md](https://github.com/RedCarrottt/nvmon/blob/master/README.md) and pushed it to the repository.

Please check it.

**Comment by ghost** [comment]
Amazing, Will let you know shortly on some testing!

**Comment by RedCarrottt** [comment]
Since I made README.md, I close this issue.
