### ISSUE TITLE
changes for windows..

### ISSUE THREAD

**Issue by ghost** [RedCarrottt/nvmon#2]
Here are some changes for the monitor to work on Windows 10 & Server 16.

**nvmon-smi-server.js**

To pull IP from windows 10, still works on Ubuntu:

line 19: 
```
//if(ifname.startsWith("enp") || ifname.startsWith("eth")) {
                hostname = iface.address;
                    //}
```

Also nvidia-smi.exe from C:\Program Files\NVIDIA Corporation\NVSMI needs to be linked , Or it can be copied over to /nvmon folder for full functionality. 

------

Lastly, How is entry for mutli monitor?

```
var NvmonConfig = {
serverList: [
    {name: "tensorA", ip: "10.0.0.17"}
    {name: "tensorB", ip: "10.0.0.102"}
]
};
 
```

Is not working for me.?

**Comment by RedCarrottt** [comment]
@rendsolve Thank you. I will apply the Windows 10 support to the source code soon.
Actually, since my target system is fully Ubuntu servers, there are many hard-coded spots.

Regarding your last question, you need a comma between two server list entries.
The following config will work.
```
var NvmonConfig = {
serverList: [
    {name: "tensorA", ip: "10.0.0.17"},
    {name: "tensorB", ip: "10.0.0.102"}
]
};
```

**Comment by RedCarrottt** [comment]
I've update the ```nvmon-smi-server.js``` to support Windows 10. - f357653f34069a643a97c279ad1eb1d96b587b63
Therefore, I close this issue.
